export const clients = [
    "/assets/images/client/1.webp",
    "/assets/images/client/2.webp",
    "/assets/images/client/3.webp",
    "/assets/images/client/4.webp",
    "/assets/images/client/5.webp",
    "/assets/images/client/6.webp",
    "/assets/images/client/7.webp",
    "/assets/images/client/8.webp",
    "/assets/images/client/9.webp",
    "/assets/images/client/10.webp",
    "/assets/images/client/11.webp",
    "/assets/images/client/12.webp",
    "/assets/images/client/13.webp",
    "/assets/images/client/14.webp",
    "/assets/images/client/15.webp",
    "/assets/images/client/16.webp",
    "/assets/images/client/17.webp",
    "/assets/images/client/18.webp",
    "/assets/images/client/19.webp",
    "/assets/images/client/20.webp",
    "/assets/images/client/21.webp",
    "/assets/images/client/22.webp",
    "/assets/images/client/23.webp",
    "/assets/images/client/24.webp",
    "/assets/images/client/25.webp",
    "/assets/images/client/26.webp",
    "/assets/images/client/27.webp",
    "/assets/images/client/28.webp",
    "/assets/images/client/29.webp",
    "/assets/images/client/30.webp",
    "/assets/images/client/31.webp",
    "/assets/images/client/32.webp",
    "/assets/images/client/33.webp",
    "/assets/images/client/34.webp",
    "/assets/images/client/35.webp",
    "/assets/images/client/36.webp",
    "/assets/images/client/37.webp",
    "/assets/images/client/38.webp",
    "/assets/images/client/39.webp",
    "/assets/images/client/40.webp",
    "/assets/images/client/41.webp",
    "/assets/images/client/42.webp",
    "/assets/images/client/43.webp",
    "/assets/images/client/44.webp",
    "/assets/images/client/45.webp",
    "/assets/images/client/46.webp",
    "/assets/images/client/47.webp",
    "/assets/images/client/48.webp",
    "/assets/images/client/49.webp",
    "/assets/images/client/50.webp",
    "/assets/images/client/51.webp",
    "/assets/images/client/52.webp",
];
export const homeMetaData = {
    title: "WiztechBD - A Celestial Software House.",
    description: "Looking for top software development companies in Bangladesh? Here's the list of best software developers in Bangladesh with reviews that build customized software solutions.",
    keywords:
        "software development company, custom software development, IT consulting services, software solutions company, web development services, mobile app development, enterprise software development, top software development companies, digital transformation services, software outsourcing company, SEO for software companies, SEM and PPC services, digital marketing for IT companies, lead generation for software companies, content marketing for tech companies",
    openGraph: {
        title: "WiztechBD - A Celestial Software House.",
        description: "Looking for top software development companies in Bangladesh? Here's the list of best software developers in Bangladesh with reviews that build customized software solutions.",
        keywords:
            "software development company, custom software development, IT consulting services, software solutions company, web development services, mobile app development, enterprise software development, top software development companies, digital transformation services, software outsourcing company, SEO for software companies, SEM and PPC services, digital marketing for IT companies, lead generation for software companies, content marketing for tech companies",

        url: "hhttps://wiztecbd.com/",
        siteName: "MyWebsite",
    },
    twitter: {
        card: "WiztechBD - A Celestial Software House.",
        title: "WiztechBD - A Celestial Software House.",
        description: "Looking for top software development companies in Bangladesh? Here's the list of best software developers in Bangladesh with reviews that build customized software solutions.",
        keywords:
            "software development company, custom software development, IT consulting services, software solutions company, web development services, mobile app development, enterprise software development, top software development companies, digital transformation services, software outsourcing company, SEO for software companies, SEM and PPC services, digital marketing for IT companies, lead generation for software companies, content marketing for tech companies",
    },
};
export const servicesMetaData = {
    title: "Services - WiztechBD - A Celestial Software House.",
    description: "Looking for top software development companies in Bangladesh? Here's the list of best software developers in Bangladesh with reviews that build customized software solutions.",
    keywords:
        "custom app development, cloud computing services, blockchain development, ERP development, CRM software development, eCommerce website development, AI and ML development, IoT software solutions, big data analytics services, API integration services, Node.js development services, React.js developers, Python software development, Java development services, Angular developers, Kotlin app development, Flutter mobile development, .NET software development, PHP web development, Laravel development company, healthcare software development, eCommerce software solutions, fintech software development, education software development, real estate software solutions,",
    openGraph: {
        title: "Services - WiztechBD - A Celestial Software House.",
        description: "Looking for top software development companies in Bangladesh? Here's the list of best software developers in Bangladesh with reviews that build customized software solutions.",
        keywords:
            "custom app development, cloud computing services, blockchain development, ERP development, CRM software development, eCommerce website development, AI and ML development, IoT software solutions, big data analytics services, API integration services, Node.js development services, React.js developers, Python software development, Java development services, Angular developers, Kotlin app development, Flutter mobile development, .NET software development, PHP web development, Laravel development company, healthcare software development, eCommerce software solutions, fintech software development, education software development, real estate software solutions,",

        url: "hhttps://wiztecbd.com/",
        siteName: "MyWebsite",
    },
    twitter: {
        card: "Services - WiztechBD - A Celestial Software House.",
        title: "Services - WiztechBD - A Celestial Software House.",
        description: "Looking for top software development companies in Bangladesh? Here's the list of best software developers in Bangladesh with reviews that build customized software solutions.",
        keywords:
            "custom app development, cloud computing services, blockchain development, ERP development, CRM software development, eCommerce website development, AI and ML development, IoT software solutions, big data analytics services, API integration services, Node.js development services, React.js developers, Python software development, Java development services, Angular developers, Kotlin app development, Flutter mobile development, .NET software development, PHP web development, Laravel development company, healthcare software development, eCommerce software solutions, fintech software development, education software development, real estate software solutions,",
    },
};

export const feetBacks = [
    {
        id: 1,
        name: "A.M.M Nuruddin,",
        img: "/assets/images/client/Eastland Ins.jpg",
        degenation: "Sr.Executive, Vice President and Head of IT",
        rating: 5,
        platform: "Eastland Insurance Company Ltd (EICL)",
        coment: "Fantastic experience with their software development team! The custom solutions they built are exactly what we needed to streamline our operations.",
    },
    {
        id: 2,
        name: "Md. Hisan Khatib Khan Babu",
        img: "/assets/images/client/IMG-20250210-WA0005.jpg",
        degenation: "Director",
        rating: 4.5,
        platform: "Mother’s Glow",
        coment: "Impressed with their digital marketing services! Our website traffic has doubled since they took over our campaigns.",
    },
    {
        id: 3,
        name: "Md Abu Naser Mizan",
        img: "/assets/images/client/1.webp",
        degenation: "Assistant Director",
        rating: 5,
        platform: "Election Monitoring Forum NGO ",
        coment: "Great team for software development! They understood our requirements perfectly and delivered ahead of schedule.",
    },
    {
        id: 4,
        name: "Mithila Rozario",
        img: "/assets/images/client/MIRPUR TUTOR.webp",
        degenation: "Founder & Owner",
        rating: 5,
        platform: "Mirpur Tutor",
        coment: "Digital marketing at its best! The strategies they implemented boosted our engagement and brought in more qualified leads.",
    },
    {
        id: 5,
        name: "Md. Nazim Uddin",
        img: "/assets/images/client/deal24.webp",
        degenation: "Founder",
        rating: 5,
        platform: "Deal24 ",
        coment: "Excellent software development services. The product they delivered is both innovative and user-friendly.",
    },
    {
        id: 6,
        name: "Rafi Mahmud",
        img: "/assets/images/client/F-com.webp",
        degenation: "Owner",
        rating: 4.5,
        platform: "F-Commerce",
        coment: "Absolutely love the graphic design work they did for our brand! The visuals perfectly capture our identity and have elevated our marketing materials.",
    },
    {
        id: 7,
        name: "MD. Nazmul Hasan Bhuiyan",
        img: "/assets/images/client/36.webp",
        degenation: "Proprietor",
        rating: 5,
        platform: "PerfectoBD",
        coment: "Partnering with this team for our e-commerce store was a game-changer! The platform is user-friendly, and sales have significantly increased.",
    },
    {
        id: 8,
        name: "MD. Selim Uddin",
        img: "/assets/images/client/Angoragh.webp",
        degenation: "Proprietor",
        rating: 5,
        platform: "Anghorag ",
        coment: "Impressive e-commerce solutions! Their expertise in optimizing the shopping experience has made a huge difference in customer satisfaction.",
    },
    {
        id: 9,
        name: "Mehedi Hasan",
        img: "/assets/images/client/F-com2.webp",
        degenation: "Owner",
        rating: 5,
        platform: "F-commerce",
        coment: "Creative and professional graphic design services! They turned our ideas into stunning visuals that really resonate with our audience.",
    },
    {
        id: 10,
        name: "Sowkat Ali",
        img: "/assets/images/client/Training.webp",
        degenation: "Trainee",
        rating: 5,
        platform: "Software Development Training ",
        coment: "The IT training programs are top-notch! The courses were thorough, and I feel much more confident with the new skills I’ve learned.",
    },
    {
        id: 11,
        name: "Mohin Uddin Hridoy",
        img: "/assets/images/client/logo.png",
        degenation: "Proprietor",
        rating: 5,
        platform: "MediSource",
        coment: "Our new e-commerce platform is fantastic! It’s easy to navigate, and our customers love the streamlined checkout process.",
    },
    {
        id: 12,
        name: "Jabed Ali",
        img: "/assets/images/client/Training.webp",
        degenation: "Trainee",
        rating: 5,
        platform: "IT Training",
        coment: "Highly recommend their IT training sessions! The trainers are experienced, and the hands-on approach really helped me grasp complex topics.",
    },
    {
        id: 13,
        name: "C. Rahman",
        img: "/assets/images/client/38.webp",
        degenation: "Founder & CEO",
        rating: 5,
        platform: "Sheba One Ltd",
        coment: "Development & seamless integration and support for our e-commerce site. Our sales have increased thanks to their fantastic design and user experience!",
    },

    {
        id: 15,
        name: "Latifur Rahman",
        img: "/assets/images/client/exambuzz.webp",
        degenation: "Founder",
        rating: 5,
        platform: "ExamBuzz ",
        coment: "Impressive IT development services! They delivered an Exam System Solution that solved our unique business challenges efficiently.",
    },
    {
        id: 16,
        name: "Ruhul Amin Robin",
        img: "/assets/images/client/lx.webp",
        degenation: "Managing Director",
        rating: 5,
        platform: "Literature Express ",
        coment: "Couldn't be happier with the Job Preparation System they developed for us. It's reliable, scalable, and has made our processes much more efficient.",
    },
    {
        id: 17,
        name: "Riyan Ahmed",
        img: "/assets/images/client/Training.webp",
        degenation: "Trainee",
        rating: 5,
        platform: "Computer Training",
        coment: "The IT training sessions were incredibly insightful. I feel much more proficient in software development and cybersecurity now.",
    },
    {
        id: 18,
        name: "Hrituporna Debnath",
        img: "/assets/images/client/Upwork-Logo.png",
        degenation: "Owner",
        rating: 5,
        platform: "Upwork",
        coment: "Highly skilled and talented designers! They created stunning visuals for our website and marketing materials that really stand out.",
    },
    {
        id: 19,
        name: "Md Abu Naser Mizan ",
        img: "/assets/images/client/saarc.webp",
        degenation: "Assistant Director",
        rating: 5,
        platform: "SAARC Human Rights Foundation ",
        coment: "From start to finish, their software development process was smooth and professional. The solution they built fits our needs perfectly.",
    },
    {
        id: 20,
        name: "Engg. Md Reazul Islam",
        img: "/assets/images/client/24.webp",
        degenation: "IT Head",
        rating: 5,
        platform: "Educity ",
        coment: "The custom e-learning system they developed has streamlined our operations and improved learning process. Highly recommend it!",
    },
];
export const socialLinks = [
    { href: "https://www.facebook.com/wiztecbd", icon: "facebook.webp", alt: "Facebook" },
    { href: "https://wa.me/+8801600299169", icon: "whatsapp.webp", alt: "WhatsApp" },
    { href: "https://www.instagram.com/wiztecbd_?igsh=MXVtZHViaWNucnljMw==", icon: "Instragram.webp", alt: "Instagram" },
    { href: "https://www.linkedin.com/company/wiztecbd", icon: "likn.webp", alt: "LinkedIn" },
    { href: "https://join.skype.com/invite/ti82mbuKUXO9", icon: "sky.webp", alt: "Skype" },
    { href: "http://t.me/wiztecbd", icon: "Telegram.webp", alt: "Telegram" },
    { href: "https://x.com/Wiztecsoft", icon: "x twi.webp", alt: "Twitter (X)" },
    { href: "http://www.youtube.com/@wizardsoftwaretechnologyba7240", icon: "youtube.webp", alt: "YouTube" },
    { href: "https://www.pinterest.com/wiztecbd/", icon: "pinterest.webp", alt: "Pinterest" },
];
