export const teamData = [
    {
        id: 5,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Sobnoor-A-Jannat",
        department: "Researcher & Analyst",
        img: "/assets/images/team/Sobnoor-A-Jannat.png",
        alt: "Sobnoor",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 10,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Akidul Islam",
        department: "Software Specialist",
        img: "/assets/images/team/Akidul Islam.png",
        alt: "Akidul",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 1,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Syed Fahim Shahariar",
        department: "Manager (Admin & IT)",
        img: "/assets/images/team/Asset 9.png",
        alt: "Syed Fahim Shahariar",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 45,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "afifatun jannat",
        department: "bussiness analyst",
        img: "/assets/images/team/samim.jpeg",
        alt: "jannat",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 2,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "MD. Azharul Islam",
        department: "Software Engineer",
        img: "/assets/images/team/azhar saheb.jpeg",
        alt: "MD. Azharul Islam",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 3,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "MD. Jueal Hossain",
        department: "Jr. Software Engineer",
        img: "/assets/images/team/md jueal.png",
        alt: "Jueal",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 44,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Imam Hossain Shamim",
        department: "UI/UX designer",
        img: "/assets/images/team/samim.jpeg",
        alt: "Imam Hossain Shamim",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },

    {
        id: 4,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Shahriar Kibria",
        department: "Sr. Executive Officer",
        img: "/assets/images/team/Shahriar Kibria.png",
        alt: "Shahriar",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },

    {
        id: 6,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Ezazul Haque Lemon",
        department: "Business Development Executive",
        img: "/assets/images/team/Ezazul Haque Lemon.png",
        alt: "Ezazul",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 7,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Sabbir Hussain",
        department: "IT Consultant",
        img: "/assets/images/team/Sabbir Hussain.png",
        alt: "Sabbir",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 8,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Alif Altaf Hussain",
        department: "IT Consultant",
        img: "/assets/images/team/Alif Altaf Hussain.png",
        alt: "Alif",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 9,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Prodip Ghosh",
        department: "Android Developer",
        img: "/assets/images/team/Prodip Ghosh.png",
        alt: "Alif",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },

    {
        id: 12,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Md Mosfeq Anik",
        department: "Programmer",
        img: "/assets/images/team/Md Mosfeq Anik.png",
        alt: "Anik",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 13,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Sahab Uddin",
        department: "Web Developer",
        img: "/assets/images/team/Sahab Uddin.png",
        alt: "Sahab",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 14,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Md. Anamur Rabby",
        department: "Content Developer",
        img: "/assets/images/team/Anamur Rabby.png",
        alt: "Rabby",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 15,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Sobuz Ahmed",
        department: "Hardware Specialist",
        img: "/assets/images/team/Sobuz Ahmed.png",
        alt: "sa",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 16,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Shamsunnahar",
        department: "HR Accounts",
        img: "/assets/images/team/Shamsunnahar.png",
        alt: "Shamsunnahar",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 17,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Kawsar Hossain",
        department: "Marketing Executive",
        img: "/assets/images/team/Kawsar Hossain.png",
        alt: "Kawsar Hossain",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 18,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Imtiaz Ahmed",
        department: "Counsellor",
        img: "/assets/images/team/Imtiaz Ahmed.png",
        alt: "Imtiaz Ahmed",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 19,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Shahidullah Rana",
        department: "Counsellor",
        img: "/assets/images/team/Shahidullah Rana.png",
        alt: "Shahidullah Rana",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 20,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Moshiur Rahman Shanto",
        department: "Brand Ambassador",
        img: "/assets/images/team/Moshiur Rahman Shanto.png",
        alt: "Moshiur Rahman Shanto",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 21,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Shahriar Alam Shanto",
        department: "Project and Design Admin",
        img: "/assets/images/team/Shahriar.jpg",
        alt: "Shahriar Alam Shanto",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 22,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Abu Tanzin Khan Sani",
        department: "Business Development Executive",
        img: "/assets/images/team/Sani bhai.png",
        alt: "Sani",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 23,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Mortuza Ahmed",
        department: "Software Engineer",
        img: "/assets/images/team/Mortuza bhai.png",
        alt: "Mortuza Ahmed",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 24,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Md. Ali Akbar",
        department: "Software Engineer",
        img: "/assets/images/team/ali akbar.jpg",
        alt: "Md. Ali Akbar",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 25,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Mehedi Hasan",
        department: "Software Engineer",
        img: "/assets/images/team/md hossen.jpg",
        alt: "Mehedi Hasan",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 26,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Anik Chandra Debnath",
        department: "UI/UX Developer",
        img: "/assets/images/team/Asset 4.png",
        alt: "Anik Chandra Debnath",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 27,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "S.M.Al Zobaer",
        department: "HR Executive",
        img: "/assets/images/team/Asset 6.png",
        alt: "S.M.Al Zobaer",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },

    {
        id: 28,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Rahat Hossain Pollob",
        department: "Business Development & Planning Executive",
        img: "/assets/images/team/Asset 13.png",
        alt: "Rahat Hossain Pollob",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },

    {
        id: 29,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "MD. Hafiz Al Foisal",
        department: "Software Engineer",
        img: "/assets/images/team/Screenshot_2.png",
        alt: "MD. Hafiz Al Foisal",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 30,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "MD. Rasel Hossain",
        department: "Mobile Application Intern",
        img: "/assets/images/team/Screenshot_3.png",
        alt: "MD. Rasel Hossain",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 31,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Habibur Rahman",
        department: "UI/UX Intern",
        img: "/assets/images/team/Screenshot_4.png",
        alt: "Habibur Rahman",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 32,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Aminur Rahman",
        department: "UI/UX Intern",
        img: "/assets/images/team/Screenshot_5.png",
        alt: "Aminur Rahman",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 33,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Mehedi Hasan Sarkar",
        department: "Mobile Application Developer",
        img: "/assets/images/team/Mehedi Hasan Mobile App.jpg",
        alt: "Mehedi Hasan Sarkar",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 34,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Mehedi Hasan John",
        department: "Web Developer Intern",
        img: "/assets/images/team/rsz_102.png",
        alt: "Mehedi Hasan John",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 35,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Fatema Islam",
        department: "UI/UX Intern",
        img: "/assets/images/team/rsz_04.png",
        alt: "Fatema Islam",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 36,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Sarna Khatun",
        department: "Web Developer Intern",
        img: "/assets/images/team/03.png",
        alt: "Sarna Khatun",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
    {
        id: 37,
        social: { facebook: "#", instagram: "#", twitter: "#", linkedin: "#" },
        name: "Easin Md. Hosen",
        department: "Mobile App Developer Intern",
        img: "/assets/images/team/EASIN-PP.jpg",
        alt: "Easin Md. Hosen",
        description: "Glavi amet ritnisl libero molestie ante ut fringilla purus eros quis glavrid from dolor amet iquam lorem bibendum",
    },
];
